version: '3'

services: 

    nginx:

        image: nginx
        ports:
            - 8080:80
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/www
        depends_on: 
            - php-fpm
            - mariadb
    php-fpm:
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes: 
            - ./app:/var/www
        
    mariadb:
        build:
            context: ./mariadb
            dockerfile: Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment: 
            MYSQL_DATABASE: laraveldb
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - ./mariadb/data:/var/lib/mysql
            - ./mariadb/config:/etc/mysql/conf.d

    phpmyadmin:
        image: phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_PORT: 3306
            PMA_HOSTS: mariadb
       